import { test, expect, _electron as electron } from '@playwright/test';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';

test('configure, create, run, message, stop and restore using isolated storage', async ({}, info) => {
  const root = await mkdtemp(join(tmpdir(), 'ade-e2e-'));
  const repo = join(root,'repo'); const userData=join(root,'userData'); await mkdir(repo);await mkdir(userData);
  execFileSync('git',['init',repo],{windowsHide:true});
  const environment = {...process.env,ADE_TEST_REPO:repo,ADE_TEST_USER_DATA:userData};delete environment.ADE_RENDERER_URL;
  let app: Awaited<ReturnType<typeof electron.launch>> | undefined;
  const launch=async()=>{app=await electron.launch({args:[resolve('tests/e2e/desktop-fixture.cjs')],env:environment});return app.firstWindow();};
  try {
    let page=await launch();
    page.on('pageerror', error => console.error('Renderer error:',error));
    await page.getByRole('button',{name:'Selecione um projeto'}).click();
    await expect(page.locator('.workspace-switcher')).toContainText('repo');
    await page.getByRole('navigation',{name:'Navegação principal'}).getByRole('button',{name:/^Tarefas/}).click();
    await expect(page.getByRole('button',{name:'Nova tarefa',exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Configurações',exact:true}).first().click();
    await expect(page.getByRole('heading',{name:'Configurações',exact:true})).toBeVisible();
    await expect(page.locator('.task-details-sidebar')).toHaveCount(0);
    await expect(page.locator('.multi-agent-panel')).toHaveCount(0);
    await page.getByLabel(/Provider deste projeto/).selectOption('codex');
    await page.getByRole('button',{name:'Salvar configurações'}).click();
    await expect(page.getByText('Configurações salvas.')).toBeVisible();
    for (const size of [{width:1440,height:900},{width:1600,height:900},{width:1920,height:1080}]) {
      await page.setViewportSize(size);
      await expect(page.getByRole('button',{name:'Salvar configurações'})).toBeVisible();
      await page.screenshot({path:info.outputPath(`settings-${size.width}.png`)});
    }
    await page.getByRole('navigation',{name:'Navegação principal'}).getByRole('button',{name:/^Tarefas/}).click();
    await page.getByRole('button',{name:'Nova tarefa',exact:true}).click();
    await page.getByRole('button',{name:'Criar tarefa',exact:true}).focus();
    await page.keyboard.press('Tab');
    await expect(page.getByRole('button',{name:'Fechar',exact:true})).toBeFocused();
    await page.keyboard.press('Shift+Tab');
    await expect(page.getByRole('button',{name:'Criar tarefa',exact:true})).toBeFocused();
    await page.getByLabel('Descrição',{exact:true}).fill('Implementar autenticação');
    await page.getByRole('button',{name:'Criar tarefa',exact:true}).click();
    await page.locator('.kanban-task').filter({hasText:'Implementar autenticação'}).click();
    await page.getByRole('button',{name:'Nova execução',exact:true}).click();
    await page.getByRole('button',{name:'Iniciar agentes',exact:true}).click();
    await page.locator('.multi-agent-panel').getByRole('button',{name:'Agentes',exact:true}).click();
    await page.getByText(/Mensagens dos agentes/).click();
    await expect(page.locator('.conversation-stream').getByText('Execução de teste pronta.',{exact:true})).toBeVisible();
    await page.getByLabel('Mensagem para os agentes').fill('Revise segurança');
    await page.getByLabel('Mensagem para os agentes').press('Control+Enter');
    await expect(page.locator('.conversation-stream').getByText('Recebido: Revise segurança',{exact:true})).toBeVisible();
    await expect(page.locator('.agent-session-header h2')).toContainText('Execu');
    await expect(page.locator('.multi-agent-panel')).toBeVisible();
    await page.screenshot({path:info.outputPath('multi-agent.png')});
    await page.getByRole('button',{name:'Encerrar',exact:true}).click();
    await expect(page.locator('.runtime-participant-status')).toHaveText('Parado');
    await app!.close();app=undefined;
    page=await launch();
    await page.getByRole('navigation',{name:'Navegação principal'}).getByRole('button',{name:/^Execuções/}).click();
    await page.getByRole('button',{name:/Ver event stream/}).first().click();
    await page.locator('.multi-agent-panel').getByRole('button',{name:'Agentes',exact:true}).click();
    await page.getByText(/Mensagens dos agentes/).click();
    await expect(page.getByRole('heading',{name:'Implementar autenticação',exact:true})).toBeVisible();
    await expect(page.locator('.conversation-stream').getByText('Recebido: Revise segurança',{exact:true})).toBeVisible();
    await page.getByRole('button',{name:'Configurações',exact:true}).first().click();
    await expect(page.getByLabel(/Provider deste projeto/)).toHaveValue('codex');
    await page.getByLabel(/Provider padrão da ADE/).selectOption('opencode');
    await page.getByRole('navigation',{name:'Navegação principal'}).getByRole('button',{name:/^Tarefas/}).click();
    await expect(page.getByRole('heading',{name:'Descartar alterações?'})).toBeVisible();
    await page.getByRole('button',{name:'Continuar editando'}).click();
    await expect(page.getByLabel(/Provider padrão da ADE/)).toHaveValue('opencode');
    await page.getByRole('button',{name:'Descartar',exact:true}).click();
    await page.getByRole('button',{name:'Configurações',exact:true}).first().click();
    await expect(page.getByLabel(/Provider padrão da ADE/)).toHaveValue('codex');
    await app!.evaluate(({ BrowserWindow }) => { BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(2); });
    await expect(page.getByLabel(/Provider padrão da ADE/)).toBeVisible();
    await page.getByRole('button',{name:'Salvar configurações'}).scrollIntoViewIfNeeded();
    await expect(page.getByRole('button',{name:'Salvar configurações'})).toBeInViewport();
    await page.screenshot({path:info.outputPath('settings-zoom-200.png')});
  } finally { await app?.close();await rm(root,{recursive:true,force:true}); }
});
